name: test-n-stuff
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install repository
        uses: actions/checkout@v6
      - name: Install dependencies
        run: npm ci
      - name: lint command
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install repository
        uses: actions/checkout@v6
      - name: Install dependencies
        run: npm ci
      - name: Test da code ma frend
        run: npm test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Install repository
        uses: actions/checkout@v6
      - name: Install dependencies
        run: npm ci
      - name: Building command
        run: npm run build
